#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width        8
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

# set background
/home/tk/.fehbg &

~/.config/bspwm/panel &
compton &

redshift -t 6400:4000 &
